
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:7 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Darwin - 23.0.0 - arm64
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /Library/Developer/CommandLineTools/usr/bin/CC 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      ld: library 'System' not found
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /Library/Developer/CommandLineTools/usr/bin/CC 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is AppleClang, found in:
        /Users/tand/oronyx/ornyxos/cmake-build-debug/CMakeFiles/3.29.6/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:1178 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
      Apple clang version 15.0.0 (clang-1500.3.9.4)
      Target: arm64-apple-darwin23.0.0
      Thread model: posix
      InstalledDir: /Library/Developer/CommandLineTools/usr/bin
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:1165 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Checking whether the ASM compiler is AppleClang using "--version" matched "(Apple (clang|LLVM) version)":
      Apple clang version 15.0.0 (clang-1500.3.9.4)
      Target: arm64-apple-darwin23.0.0
      Thread model: posix
      InstalledDir: /Library/Developer/CommandLineTools/usr/bin
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:67 (try_compile)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:7 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "/Users/tand/oronyx/ornyxos/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-aRfmQj"
      binary: "/Users/tand/oronyx/ornyxos/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-aRfmQj"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "-L/usr/local/opt/llvm/lib"
      CMAKE_OSX_DEPLOYMENT_TARGET: ""
      CMAKE_OSX_SYSROOT: ""
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/Users/tand/oronyx/ornyxos/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-aRfmQj'
        
        Run Build Command(s): /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_a7c92/fast
        /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_a7c92.dir/build.make CMakeFiles/cmTC_a7c92.dir/build
        Building CXX object CMakeFiles/cmTC_a7c92.dir/CMakeCXXCompilerABI.cpp.obj
        /Library/Developer/CommandLineTools/usr/bin/CC   -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_a7c92.dir/CMakeCXXCompilerABI.cpp.obj -MF CMakeFiles/cmTC_a7c92.dir/CMakeCXXCompilerABI.cpp.obj.d -o CMakeFiles/cmTC_a7c92.dir/CMakeCXXCompilerABI.cpp.obj -c /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeCXXCompilerABI.cpp
        Apple clang version 15.0.0 (clang-1500.3.9.4)
        Target: arm64-apple-darwin23.0.0
        Thread model: posix
        InstalledDir: /Library/Developer/CommandLineTools/usr/bin
        ignoring nonexistent directory "/usr/include/c++/v1"
        ignoring nonexistent directory "/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1"
         "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple arm64-apple-macosx14.0.0 -Wundef-prefix=TARGET_OS_ -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCXXCompilerABI.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=non-leaf -fno-strict-return -ffp-contract=on -fno-rounding-math -funwind-tables=1 -fobjc-msgsend-selector-stubs -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -target-cpu apple-m1 -target-feature +v8.5a -target-feature +crc -target-feature +lse -target-feature +rdm -target-feature +crypto -target-feature +dotprod -target-feature +fp-armv8 -target-feature +neon -target-feature +fp16fml -target-feature +ras -target-feature +rcpc -target-feature +zcm -target-feature +zcz -target-feature +fullfp16 -target-feature +sm4 -target-feature +sha3 -target-feature +sha2 -target-feature +aes -target-abi darwinpcs -debugger-tuning=lldb -target-linker-version 1053.12 -v -fcoverage-compilation-dir=/Users/tand/oronyx/ornyxos/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-aRfmQj -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0 -dependency-file CMakeFiles/cmTC_a7c92.dir/CMakeCXXCompilerABI.cpp.obj.d -skip-unused-modulemap-deps -MT CMakeFiles/cmTC_a7c92.dir/CMakeCXXCompilerABI.cpp.obj -sys-header-deps -I/opt/homebrew/include -internal-isystem /usr/local/include -internal-isystem /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include -internal-externc-isystem /usr/include -internal-externc-isystem /Library/Developer/CommandLineTools/usr/include -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-final-dtor-non-final-class -Wno-extra-semi-stmt -Wno-misleading-indentation -Wno-quoted-include-in-framework-header -Wno-implicit-fallthrough -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-elaborated-enum-base -Wno-reserved-identifier -Wno-gnu-folding-constant -fdeprecated-macro -fdebug-compilation-dir=/Users/tand/oronyx/ornyxos/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-aRfmQj -ferror-limit 19 -stack-protector 1 -fstack-check -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fno-cxx-modules -fcxx-exceptions -fexceptions -fmax-type-align=16 -fcommon -fcolor-diagnostics -clang-vendor-feature=+disableNonDependentMemberExprInCurrentInstantiation -fno-odr-hash-protocols -clang-vendor-feature=+enableAggressiveVLAFolding -clang-vendor-feature=+revert09abecef7bbf -clang-vendor-feature=+thisNoAlignAttr -clang-vendor-feature=+thisNoNullAttr -mllvm -disable-aligned-alloc-awareness=1 -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_a7c92.dir/CMakeCXXCompilerABI.cpp.obj -x c++ /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeCXXCompilerABI.cpp
        clang -cc1 version 15.0.0 (clang-1500.3.9.4) default target arm64-apple-darwin23.0.0
        ignoring nonexistent directory "/usr/include"
        #include "..." search starts here:
        #include <...> search starts here:
         /opt/homebrew/include
         /usr/local/include
         /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include
         /Library/Developer/CommandLineTools/usr/include
         /System/Library/Frameworks (framework directory)
         /Library/Frameworks (framework directory)
        End of search list.
        Linking CXX executable cmTC_a7c92
        /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a7c92.dir/link.txt --verbose=1
        /Library/Developer/CommandLineTools/usr/bin/CC -L/usr/local/opt/llvm/lib -v CMakeFiles/cmTC_a7c92.dir/CMakeCXXCompilerABI.cpp.obj -o cmTC_a7c92
        Apple clang version 15.0.0 (clang-1500.3.9.4)
        Target: arm64-apple-darwin23.0.0
        Thread model: posix
        InstalledDir: /Library/Developer/CommandLineTools/usr/bin
         "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -dynamic -arch arm64 -platform_version macos 14.0.0 14.0.0 -o cmTC_a7c92 -L/usr/local/opt/llvm/lib -L/opt/homebrew/lib CMakeFiles/cmTC_a7c92.dir/CMakeCXXCompilerABI.cpp.obj -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/lib/darwin/libclang_rt.osx.a
        ld: warning: search path '/usr/local/opt/llvm/lib' not found
        ld: library 'System' not found
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        make[1]: *** [cmTC_a7c92] Error 1
        make: *** [cmTC_a7c92/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:7 (project)"
    checks:
      - "Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/CC"
    directories:
      source: "/Users/tand/oronyx/ornyxos/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-vxiNpA"
      binary: "/Users/tand/oronyx/ornyxos/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-vxiNpA"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "-L/usr/local/opt/llvm/lib"
      CMAKE_OSX_DEPLOYMENT_TARGET: ""
      CMAKE_OSX_SYSROOT: ""
    buildResult:
      variable: "CMAKE_CXX_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/Users/tand/oronyx/ornyxos/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-vxiNpA'
        
        Run Build Command(s): /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_c1764/fast
        /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_c1764.dir/build.make CMakeFiles/cmTC_c1764.dir/build
        Building CXX object CMakeFiles/cmTC_c1764.dir/testCXXCompiler.cxx.obj
        /Library/Developer/CommandLineTools/usr/bin/CC   -fcolor-diagnostics -MD -MT CMakeFiles/cmTC_c1764.dir/testCXXCompiler.cxx.obj -MF CMakeFiles/cmTC_c1764.dir/testCXXCompiler.cxx.obj.d -o CMakeFiles/cmTC_c1764.dir/testCXXCompiler.cxx.obj -c /Users/tand/oronyx/ornyxos/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-vxiNpA/testCXXCompiler.cxx
        Linking CXX executable cmTC_c1764
        /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c1764.dir/link.txt --verbose=1
        /Library/Developer/CommandLineTools/usr/bin/CC -L/usr/local/opt/llvm/lib  CMakeFiles/cmTC_c1764.dir/testCXXCompiler.cxx.obj -o cmTC_c1764
        ld: warning: search path '/usr/local/opt/llvm/lib' not found
        ld: library 'System' not found
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        make[1]: *** [cmTC_c1764] Error 1
        make: *** [cmTC_c1764/fast] Error 2
        
      exitCode: 2
...
