if(NOT DEFINED ARCH)
    set(ARCH "x86_64")
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")
set(CMAKE_SYSTEM_NAME Generic)

set(CMAKE_C_COMPILER ${ARCH}-elf-gcc)
set(CMAKE_CXX_COMPILER ${ARCH}-elf-g++)
set(CMAKE_ASM_COMPILER ${ARCH}-elf-gcc)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_OSX_DEPLOYMENT_TARGET "")
set(CMAKE_OSX_SYSROOT "")