name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
        build_type: [ Release ]

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install x86_64-elf-gcc xorriso cmake

      - name: Configure CMake
        run: |
          cmake -E make_directory ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config ${{ matrix.build_type }}

      - name: Update Kernel Size Badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          SIZE=$(stat -f %z build/kernel.elf)
          SIZE_KB=$((SIZE / 1024))
          BADGE_URL="https://img.shields.io/badge/Kernel%20Size-${SIZE_KB}KB-blue"
          
          sed -i '' "s|!\[Kernel Size\](https://img.shields.io/badge/Kernel%20Size-[0-9]*KB-blue)|![Kernel Size](${BADGE_URL})|" README.md
          
          # If there are changes, commit and push them
          if git diff --quiet README.md; then
            echo "No changes to kernel size"
          else
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "[auto]: update kernel size to ${SIZE_KB}KB [skip ci]"
            git push
          fi